# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ChatCli < Formula
  desc "chat-cli is a command line tool for working with llms on Amazon Bedrock"
  homepage "https://github.com/chat-cli/chat-cli/"
  version "0.3.4"

  on_macos do
    on_intel do
      url "https://github.com/chat-cli/chat-cli/releases/download/v0.3.4/chat-cli_Darwin_x86_64.tar.gz"
      sha256 "428f1c668874f814349b5ec980e6b2c72308758a69ea200285f77d83ffcac330"

      def install
        bin.install "chat-cli"
      end
    end
    on_arm do
      url "https://github.com/chat-cli/chat-cli/releases/download/v0.3.4/chat-cli_Darwin_arm64.tar.gz"
      sha256 "523f83884d839b4916ef3cf8d64fa053216762baa90eaccdc3a43935ca730040"

      def install
        bin.install "chat-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chat-cli/chat-cli/releases/download/v0.3.4/chat-cli_Linux_x86_64.tar.gz"
        sha256 "2b08d4bd9a8b61b82cb5b9a664112c7f723f5d1eb1d7190be99a11cdf2c5d817"

        def install
          bin.install "chat-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chat-cli/chat-cli/releases/download/v0.3.4/chat-cli_Linux_arm64.tar.gz"
        sha256 "873c8c67e7fc3af696332085c58f81abfeb84043207336546078e00178b3178a"

        def install
          bin.install "chat-cli"
        end
      end
    end
  end
end
