# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ChatCli < Formula
  desc "chat-cli is a command line tool for working with llms on Amazon Bedrock"
  homepage "https://github.com/chat-cli/chat-cli/"
  version "0.4.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chat-cli/chat-cli/releases/download/v0.4.4/chat-cli_Darwin_x86_64.tar.gz"
      sha256 "bd2e53f8b591b1bc88ede1463b3fdae531180ac867bd496df7b443c94d4888e4"

      def install
        bin.install "chat-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chat-cli/chat-cli/releases/download/v0.4.4/chat-cli_Darwin_arm64.tar.gz"
      sha256 "ff118d3ea91d9ede6224f037ee43e8da73b31a4898a3a9c73ee6b0d84d3d66bb"

      def install
        bin.install "chat-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chat-cli/chat-cli/releases/download/v0.4.4/chat-cli_Linux_x86_64.tar.gz"
        sha256 "7fb01110dffe6bca698ebe031624966fdbec61b77d19f98d9aef2e25e86efeeb"

        def install
          bin.install "chat-cli"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chat-cli/chat-cli/releases/download/v0.4.4/chat-cli_Linux_arm64.tar.gz"
        sha256 "e73d4d574f7753f4b2e575fb5b31a29529dc6658a058156ce45c9ce37049df91"

        def install
          bin.install "chat-cli"
        end
      end
    end
  end
end
