# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ChatCli < Formula
  desc "chat-cli is a command line tool for working with llms on Amazon Bedrock"
  homepage "https://github.com/chat-cli/chat-cli/"
  version "0.3.5"

  on_macos do
    on_intel do
      url "https://github.com/chat-cli/chat-cli/releases/download/v0.3.5/chat-cli_Darwin_x86_64.tar.gz"
      sha256 "5dc443db898bf1b31d4235217dd43572e42c2dcf3b3a447855d43b9e63f89326"

      def install
        bin.install "chat-cli"
      end
    end
    on_arm do
      url "https://github.com/chat-cli/chat-cli/releases/download/v0.3.5/chat-cli_Darwin_arm64.tar.gz"
      sha256 "ab2c3c2c8a62172a1d09e04255c43471c8f38854bf4de7e25fef65c04d844d31"

      def install
        bin.install "chat-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chat-cli/chat-cli/releases/download/v0.3.5/chat-cli_Linux_x86_64.tar.gz"
        sha256 "abc3eac59dbf7df7dc4b59d95c748dfe0558266bd53b2d8000250ad6e3c17938"

        def install
          bin.install "chat-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chat-cli/chat-cli/releases/download/v0.3.5/chat-cli_Linux_arm64.tar.gz"
        sha256 "3c4de693f35b1399410652bbf1895e1c7fbb534a57f7f6e8f7d3077ea395318f"

        def install
          bin.install "chat-cli"
        end
      end
    end
  end
end
